schema = 3

[mod]
  [mod."github.com/akavel/rsrc"]
    version = "v0.10.2"
    hash = "sha256-QsPx3RYA2uc+qIN2LKRCvumeMedg0kIEuUOkaRvuLbs="
  [mod."github.com/armon/go-metrics"]
    version = "v0.4.1"
    hash = "sha256-usxTUHA0QQMdM6sHi2z51nmnEKMbA0qUilxJFpWHlYE="
  [mod."github.com/dchest/jsmin"]
    version = "v0.0.0-20220218165748-59f39799265f"
    hash = "sha256-siVZvjiFurNLlogmoyJf+pASJw3/8S9RuTBf3wU3ayg="
  [mod."github.com/fatih/color"]
    version = "v1.16.0"
    hash = "sha256-Aq/SM28aPJVzvapllQ64R/DM4aZ5CHPewcm/AUJPyJQ="
  [mod."github.com/golang/protobuf"]
    version = "v1.5.3"
    hash = "sha256-svogITcP4orUIsJFjMtp+Uv1+fKJv2Q5Zwf2dMqnpOQ="
  [mod."github.com/hashicorp/consul/api"]
    version = "v1.27.0"
    hash = "sha256-ssQRVhNTAqjNcR4hqu8d3Ahodr2BssCzLW9HlTc/484="
  [mod."github.com/hashicorp/errwrap"]
    version = "v1.1.0"
    hash = "sha256-6lwuMQOfBq+McrViN3maJTIeh4f8jbEqvLy2c9FvvFw="
  [mod."github.com/hashicorp/go-cleanhttp"]
    version = "v0.5.2"
    hash = "sha256-N9GOKYo7tK6XQUFhvhImtL7PZW/mr4C4Manx/yPVvcQ="
  [mod."github.com/hashicorp/go-hclog"]
    version = "v1.6.2"
    hash = "sha256-cGlKyuctpU6Jd+L1ybCoJrBwnBlHXks4CQYkTQMCxDU="
  [mod."github.com/hashicorp/go-immutable-radix"]
    version = "v1.3.1"
    hash = "sha256-65+A2HiVfS/GV9G+6/TkXXjzXhI/V98e6RlJWjxy+mg="
  [mod."github.com/hashicorp/go-multierror"]
    version = "v1.1.1"
    hash = "sha256-ANzPEUJIZIlToxR89Mn7Db73d9LGI51ssy7eNnUgmlA="
  [mod."github.com/hashicorp/go-rootcerts"]
    version = "v1.0.2"
    hash = "sha256-prifkrFs+lawGTig3GwxddR0QM9E1+IpgZWCKoOnS5M="
  [mod."github.com/hashicorp/go-sockaddr"]
    version = "v1.0.6"
    hash = "sha256-AZ2RZJGv3qGbVyPbjq1dRlnHc0orGJkgnh7gdRxkU28="
  [mod."github.com/hashicorp/golang-lru"]
    version = "v1.0.2"
    hash = "sha256-yy+5botc6T5wXgOe2mfNXJP3wr+MkVlUZ2JBkmmrA48="
  [mod."github.com/hashicorp/serf"]
    version = "v0.10.1"
    hash = "sha256-kA+c1UDJV/bVH0w3TY1XbKMvxLF8Wi23mEj5joX01Kc="
  [mod."github.com/josephspurrier/goversioninfo"]
    version = "v1.4.0"
    hash = "sha256-b1qgO7YsSSvDeH5hZcSzWM517j7aytmEz4I7CSvwFyA="
  [mod."github.com/keybase/go-crypto"]
    version = "v0.0.0-20200123153347-de78d2cb44f4"
    hash = "sha256-WCboyLAUMWPFGdw/WqQiEKn+r+dSWK7NLHjZ08G+OV8="
  [mod."github.com/mattn/go-colorable"]
    version = "v0.1.13"
    hash = "sha256-qb3Qbo0CELGRIzvw7NVM1g/aayaz4Tguppk9MD2/OI8="
  [mod."github.com/mattn/go-isatty"]
    version = "v0.0.20"
    hash = "sha256-qhw9hWtU5wnyFyuMbKx+7RB8ckQaFQ8D+8GKPkN3HHQ="
  [mod."github.com/mitchellh/go-homedir"]
    version = "v1.1.0"
    hash = "sha256-oduBKXHAQG8X6aqLEpqZHs5DOKe84u6WkBwi4W6cv3k="
  [mod."github.com/mitchellh/mapstructure"]
    version = "v1.5.0"
    hash = "sha256-ztVhGQXs67MF8UadVvG72G3ly0ypQW0IRDdOOkjYwoE="
  [mod."github.com/ncruces/zenity"]
    version = "v0.10.11"
    hash = "sha256-GQk0XCpR3qQxZm3EJadyYQOlSmoUsgxsF4RAjKKkw/8="
  [mod."github.com/randall77/makefat"]
    version = "v0.0.0-20210315173500-7ddd0e42c844"
    hash = "sha256-ogoDbLNIOCREi4b3Fc7gpmcjQqxGthMbb+FlXTTkF3U="
  [mod."github.com/rs/zerolog"]
    version = "v1.33.0"
    hash = "sha256-jT/Y/izhZiCdrDbC/ty83FGs8UQavTU+OW03O4vKFkY="
  [mod."golang.org/x/exp"]
    version = "v0.0.0-20240205201215-2c58cdc269a3"
    hash = "sha256-vNB+gyucFlvOK7ngsLleZDwDU8jySehOSPVnCmbR2X4="
  [mod."golang.org/x/image"]
    version = "v0.15.0"
    hash = "sha256-8VvBDVh7MjaZNi5hERxKyHUrOYEmTsAylxj3fkE1QVA="
  [mod."golang.org/x/net"]
    version = "v0.21.0"
    hash = "sha256-LfiqMpPtqvW/eLkfx6Ebr5ksqKbQli6uq06c/+XrBsw="
  [mod."golang.org/x/sys"]
    version = "v0.17.0"
    hash = "sha256-e0qnE+SitE02IzvnJKI4Uzpq9EOZY+zvE8Wf5b2e6Kg="
  [mod."golang.org/x/text"]
    version = "v0.14.0"
    hash = "sha256-yh3B0tom1RfzQBf1RNmfdNWF1PtiqxV41jW1GVS6JAg="
  [mod."google.golang.org/genproto/googleapis/rpc"]
    version = "v0.0.0-20240205150955-31a09d347014"
    hash = "sha256-B8ntyEaQ3CTr8VQo9zTbrESnYWZ6Lc3rMij0lvnchQM="
  [mod."google.golang.org/grpc"]
    version = "v1.61.0"
    hash = "sha256-+LvlQyeIaM0GgOQoa3rVmM9OS0UtbdK54Fvl3dgJEt8="
  [mod."google.golang.org/protobuf"]
    version = "v1.32.0"
    hash = "sha256-GJuTkMGHCzHbyK4yD5kY4oMn8wQWqgkeBK//yVDqHJk="
  [mod."gopkg.in/alexcesaro/statsd.v2"]
    version = "v2.0.0"
    hash = "sha256-Mq/RJyzMFIbXwzbOiKC3MRfCdg7vcZuXepqzuJHpTQo="
